version: "2.3"
services:
  cms_optimizer_dev:
    build:
      context: .
      dockerfile: cms_optimizer.Dockerfile
    container_name: cms_optimizer
    stdin_open: true
    shm_size: "32gb"
    #volumes:
        #- ../:/home/simpl/CM
        #- /home/fnoic/Desktop/data/box_office_data
    ports:
        - "2243:22"
    environment:
        - LOCAL_UID=${UUID}
        - LOCAL_GID=${GID}
    entrypoint: /usr/local/bin/cms_optimizer-entrypoint.sh
    command: /usr/local/bin/init.sh

  cms_optimizer:
    build:
      context: .
      dockerfile: alpine_builder.Dockerfile
    container_name: cms_optimizer_builder
    volumes:
    - ../:/compressor/mount:ro
    - ../bin:/compressor/bin
    entrypoint: /usr/local/bin/cms_optimizer-entrypoint.sh

  cms_optimizer_minimal:
    build:
      context: .
      dockerfile: alpine_minimal.Dockerfile
    container_name: cms_optimizer_minimal
